### ISSUE TITLE
Generative UI vs useChat?

### ISSUE THREAD

**Issue by zavier-sanders** [vercel/ai-chatbot#306]
Thanks a lot for all the effort you've put into this! I'm still getting the hang of things, but it looks like Generative UI is the way to go now, especially since it lets us stream components, which is pretty cool. The thing is, it only works with OpenAI at the moment. It seems like useChat can work with more providers, but then we lose the streaming feature.

So, I've got a couple of questions:

- Can we somehow use Generative UI with other providers too, like Cohere?
- Is there a way to mix Generative UI and useChat, or do we have to choose one over the other?
Would love to hear your thoughts on this.

**Comment by athrael-soju** [comment]
@zavier-sanders Generative UI works well with any LLM that has function (or tools) support. Gemini and Claude both support this on the API level with minimal code changes.

If I had collaborator access I'd be able to update the template to use any compatible provider, since it takes a while to get PRs reviewed.

**Comment by zavier-sanders** [comment]
@athrael-soju thanks for jumping in with that info! It's super helpful to know that Generative UI is compatible with any LLM like Gemini and Claude, as long as they have function support. And it sounds like making it work with these APIs isn't too much of a hassle, which is awesome.

Funny timing, I just saw Vercel dropped a new template using Gemini. I'll use that for reference now.
