### ISSUE TITLE
Selecting any of the trending memecoins throws `Cannot destructure property 'role' error`

### ISSUE THREAD

**Issue by athrael-soju** [vercel/ai-chatbot#325]
@jeremyphilemon although https://github.com/vercel/ai-chatbot/pull/324 resolves the majority of issues from using streamUI over render, this one still remains.

Simply get the trending memecoins to show and select one of them. Error attached.

![image](https://github.com/vercel/ai-chatbot/assets/25455658/dca3136f-214d-4063-a199-dd7fda64e815)

**Comment by prashantbhudwal** [comment]
@jeremyphilemon @jaredpalmer  

the messages sent to openai are not formatted properly. 

Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'.

I was testing. This works.

`const toolCallMessage: CoreMessage = {
  role: "assistant",
  content: [
    {
      type: "tool-call",
      toolName: "showStockPurchase",
      toolCallId: "8Bb6oJ1vAIRuHSIAVYmAp",
      args: z.object({
        symbol: z.string(),
        price: z.number(),
        defaultAmount: z.number(),
      }),
    },
  ],
};

const toolMessage: CoreMessage = {
  role: "tool",
  content: [
    {
      result: JSON.stringify({
        symbol: "AAPL",
        price: 150,
        defaultAmount: 100,
        status: "completed",
      }),
      type: "tool-result",
      toolCallId: "8Bb6oJ1vAIRuHSIAVYmAp",
      toolName: "showStockPurchase",
    },
  ],
};

  const all = [...messages, toolCallMessage, toolMessage];

`

**Comment by athrael-soju** [comment]
@prashantbhudwal Could you raise a PR please?

**Comment by prashantbhudwal** [comment]
> @jeremyphilemon @jaredpalmer
> 
> the messages sent to openai are not formatted properly.
> 
> Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'.
> 
> I was testing. This works.
> 
> ```ts
> const toolCallMessage: CoreMessage = {
>   role: "assistant",
>   content: [
>     {
>       type: "tool-call",
>       toolName: "showStockPurchase",
>       toolCallId: "8Bb6oJ1vAIRuHSIAVYmAp",
>       args: z.object({
>         symbol: z.string(),
>         price: z.number(),
>         defaultAmount: z.number(),
>       }),
>     },
>   ],
> };
> 
> const toolMessage: CoreMessage = {
>   role: "tool",
>   content: [
>     {
>       result: JSON.stringify({
>         symbol: "AAPL",
>         price: 150,
>         defaultAmount: 100,
>         status: "completed",
>       }),
>       type: "tool-result",
>       toolCallId: "8Bb6oJ1vAIRuHSIAVYmAp",
>       toolName: "showStockPurchase",
>     },
>   ],
> };
> 
>   const all = [...messages, toolCallMessage, toolMessage];
> ```
@athrael-soju 
This is not a solution, just a problem description. I am still learning this. So, I don't think I am the best person for the PR.

**Comment by hemik000** [comment]
Same error. Any solution?

**Comment by Spectralgo** [comment]
Same kind of error here with this error message: `Cannot destructure property 'role' of '.for' as it is undefined.
    at convertToOpenAIChatMessage`

Can't have the app reply after showing me a card.

![image](https://github.com/vercel/ai-chatbot/assets/56794425/7d745540-6751-4e7f-ba27-1141ad517faf)


Time for me to study some docs 📃 and try some implementations !! GLHF

**Comment by hemik000** [comment]
Because the new SDK uses streamUI
https://github.com/vercel/ai-chatbot/blob/095550d4dca22dc506cdbda815cab94cfe8fbe74/lib/chat/actions.tsx#L140

And old one uses a render
https://github.com/vercel/ai-chatbot/blob/d5f736128dca6efff963fa3705f728b06f8d7927/lib/chat/actions.tsx#L144

**Comment by athrael-soju** [comment]
> Because the new SDK uses streamUI
> 
> https://github.com/vercel/ai-chatbot/blob/095550d4dca22dc506cdbda815cab94cfe8fbe74/lib/chat/actions.tsx#L140
> 
> And old one uses a render
> 
> https://github.com/vercel/ai-chatbot/blob/d5f736128dca6efff963fa3705f728b06f8d7927/lib/chat/actions.tsx#L144

The bug appears when using streamUI, not render. If you revert to the previous commit it works fine with render.

**Comment by DanielhCarranza** [comment]
I have the same error after clicking on the first generated component, I update everything even nextjs but it didn't work

**Comment by fullstackwebdev** [comment]
Yes, this is an issue with the new code. I guess it should be reverted or fixed?   I tried a few things to resolve it, but wasn't able to.

**Comment by fullstackwebdev** [comment]
Yes, there is an issue with the new code.

**Comment by JoseAngelChepo** [comment]
The latest update "streamUI instead of render [#324](https://github.com/vercel/ai-chatbot/pull/324)" does not allow messages with "role: system" between conversation (only at start) with new prompt param system.

The "problem" is:
The functions also uses messages with "role: system" to register the actions or events from the user in the context conversation.

The error `Cannot destructure property 'role' error` is consequence  of the function below that return undefined for "role: system"

This function is inside of dependency ["ai": "^3.1.1"](https://github.com/vercel/ai/blob/main/packages/core/core/prompt/convert-to-language-model-prompt.ts)

```
// core/prompt/convert-to-language-model-prompt.ts
function convertToLanguageModelPrompt(prompt) {
  const languageModelMessages = [];
  if (prompt.system != null) {
    languageModelMessages.push({ role: "system", content: prompt.system });
  }
  switch (prompt.type) {
    case "prompt": {
      languageModelMessages.push({
        role: "user",
        content: [{ type: "text", text: prompt.prompt }]
      });
      break;
    }
    case "messages": {
      languageModelMessages.push(
        ...prompt.messages.map((message) => {
          switch (message.role) {
            case "user": {
              if (typeof message.content === "string") {
                return {
                  role: "user",
                  content: [{ type: "text", text: message.content }]
                };
              }
              return {
                role: "user",
                content: message.content.map(
                  (part) => {
                    var _a;
                    switch (part.type) {
                      case "text": {
                        return part;
                      }
                      case "image": {
                        if (part.image instanceof URL) {
                          return {
                            type: "image",
                            image: part.image,
                            mimeType: part.mimeType
                          };
                        }
                        const imageUint8 = convertDataContentToUint8Array(
                          part.image
                        );
                        return {
                          type: "image",
                          image: imageUint8,
                          mimeType: (_a = part.mimeType) != null ? _a : detectImageMimeType(imageUint8)
                        };
                      }
                    }
                  }
                )
              };
            }
            case "assistant": {
              if (typeof message.content === "string") {
                return {
                  role: "assistant",
                  content: [{ type: "text", text: message.content }]
                };
              }
              return { role: "assistant", content: message.content };
            }
            case "tool": {
              return message;
            }
          }
        })
      );
      break;
    }
    default: {
      const _exhaustiveCheck = prompt;
      throw new Error(`Unsupported prompt type: ${_exhaustiveCheck}`);
    }
  }
  return languageModelMessages;
}
```

 I tested in compiled module inside `node_modules/ai/rsc/dist/rsc-server.msj` function convertToLanguageModelPrompt by adding 

```
case "system": {
    return message;
}
```

Result:
<img width="892" alt="Captura de pantalla 2024-05-06 a la(s) 2 01 11 p m" src="https://github.com/vercel/ai-chatbot/assets/9273016/12a3c315-a6cb-4c1e-bed9-d23c5312948c">

This works but the correction must be made in the repository of the dependency  ["ai": "^3.1.1"](https://github.com/vercel/ai/blob/main/packages/core/core/prompt/convert-to-language-model-prompt.ts). 

And this depends on whether it is considered good practice to send system messages inside of the conversation to save new context (user events)

**Comment by ioachim-hub** [comment]
I believe the problem is that the streamUI function is pushing "function" role messages `role: 'function'` (https://github.com/vercel/ai-chatbot/blob/main/lib/chat/actions.tsx#L258C17-L258C34), but the SDK doesn't know about this role (https://github.com/vercel/ai/blob/4d458dfd1806e793b7b14acddb56ff48517b3b41/packages/openai/src/convert-to-openai-chat-messages.ts#L5)

**Comment by kevb10** [comment]
The above didn't solve my problem. There is a phantom object that is `undefined` on my end. And that's causing the error
<img width="733" alt="image" src="https://github.com/vercel/ai-chatbot/assets/7396751/66dfa6ca-2d88-4bab-b782-6903baf7754d">

Obviously a little sanity check addresses this but I'm curious where and why an operation returns `undefined` in the first place and fix it there instead.
<img width="673" alt="image" src="https://github.com/vercel/ai-chatbot/assets/7396751/5a48352a-44c7-486c-8e52-e288e0ed9af1">

**Comment by JoseAngelChepo** [comment]
> The above didn't solve my problem. There is a phantom object that is `undefined` on my end. And that's causing the error <img alt="image" width="733" src="https://private-user-images.githubusercontent.com/7396751/328949264-66dfa6ca-2d88-4bab-b782-6903baf7754d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODg5NzgsIm5iZiI6MTcxNTE4ODY3OCwicGF0aCI6Ii83Mzk2NzUxLzMyODk0OTI2NC02NmRmYTZjYS0yZDg4LTRiYWItYjc4Mi02OTAzYmFmNzc1NGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMTcxNzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmFkNjQ2YWIxODVjMDE5MzYzY2I1YjVjYTE4OGMzZTc5MWVlZTIyNTA2N2UzOWRiMzk4ZDAyYWY5ZThhMDkxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ib3dOFqiLfG0haaCgHZwHrv7TWz_H1wWs_QUFxeK5yo">
> 
> Obviously a little sanity check addresses this but I'm curious where and why an operation returns `undefined` in the first place and fix it there instead. <img alt="image" width="673" src="https://private-user-images.githubusercontent.com/7396751/328950354-5a48352a-44c7-486c-8e52-e288e0ed9af1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODg5NzgsIm5iZiI6MTcxNTE4ODY3OCwicGF0aCI6Ii83Mzk2NzUxLzMyODk1MDM1NC01YTQ4MzUyYS00NGM3LTQ4NmMtOGU1Mi1lMjg4ZTBlZDlhZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMTcxNzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDg1ZmNmODI0MTY3MmFlOWMyODJkNGY2NTdlNDU4YTk2NTMyMzJmMWQzNzIyZTI1Mjg3MWVkNzU3ZWY4N2EyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CD5ecUrYu_iATIIptr4z13DOPECjWEzywIztJsrLd6U">

you can track your messages in the function streamUI locate in `node_modules/ai/rsc/dist/rsc-server.mjs`

<img width="732" alt="Captura de pantalla 2024-05-08 a la(s) 11 23 25 a m" src="https://github.com/vercel/ai-chatbot/assets/9273016/723d44ae-ed30-42d1-ade3-779b348185a7">

Check messages before and after 

<img width="635" alt="Captura de pantalla 2024-05-08 a la(s) 11 27 36 a m" src="https://github.com/vercel/ai-chatbot/assets/9273016/19a35e45-33d1-4858-8595-8e9264dd6e46">

And you can do testing with the function `convertToLanguageModelPrompt(validatedPrompt)` to check what message return undefined

P.S. remember that you are in the dependency

**Comment by Spectralgo** [comment]
Thanks @kevb10. It didn't solve my problem either, but it's nice to see progress on this issue

**Comment by rbenhase** [comment]
@kevb10's sanity check also works for me, using [patch-package](https://github.com/ds300/patch-package) to create a patch file instead of making edits inside of `node_modules` (this way, I won't lose my changes as soon as I run `npm update` or `npm install`). Still not an ideal solution, obviously, but good enough for the time being.

Just ran 
`npm install patch-package postinstall-postinstall --save-dev`

Followed by:
`npx patch-package @ai-sdk/openai`

And the issue went away. Still interested in a more permanent solution, though.

**Comment by hemik000** [comment]
![Screenshot 2024-05-09 154441](https://github.com/vercel/ai-chatbot/assets/19568116/65a004e4-4eca-4c23-b590-f287ebac79ba)
Maybe because the production is 7 months old.

**Comment by hemik000** [comment]
Maybe because that might point to some old commit.

**Comment by ar-radcliff** [comment]
Just noting that I'm also running into this bug and have been troubleshooting it a bit today. What I've found mirrors what some of the other commenters have noted: adjusting the node_modules/ai/rsc/dist/rsc-server.msj file's convertToLanguageModelPrompt() function to handle more of the message types defined in actions.tsx (specifically 'function' and 'system') seems to eliminate the error, although it's not a good solution since it's a workaround in the dependency and I'm not clear what other effects that change might be having.

Something in the RSC framework is choking on handling message types of 'function', 'tool', 'data', and in some cases 'system' and it's causing them to become undefined messages in the chat history array, which is creating downstream problems elsewhere in the app.

![image](https://github.com/vercel/ai-chatbot/assets/169282514/71404a0c-7a4e-4910-9b26-cc80287eed31)
![image](https://github.com/vercel/ai-chatbot/assets/169282514/4a613970-7994-4022-8524-bb24c46517ee)

I'm also not clear on whether those roles are intended to be functional in the RSC or with GPT-4 and just aren't working here yet, or if the app is trying to do something it shouldn't be and using the roles incorrectly. The message role functionality is still very new to me!

**Comment by hemik000** [comment]
Replacing all function roles to assistant works. And now ai SDK version ai@3.1.5 has support for system message https://github.com/vercel/ai/blob/35a3d8e41232dea7a9bbfd4f4ab309178f7abf14/packages/core/core/prompt/message.ts#L12

**Comment by athrael-soju** [comment]
Honestly, with all the bugs combined, you're better off using the vercel-ai-src example
