### ISSUE TITLE
API suuport

### ISSUE THREAD

**Issue by ceyxasm** [vercel/ai-chatbot#418]
Hey Team, 
Nice work.
I wanted to ask if there is an API support/documentation for this.

I already have a webapp and I want to add a chatbot to it. Can I use this to do the same?
If yes, then how?

**Comment by jb-dev1** [comment]
There is a significant amount of documentation since this is a major Vercel AI SDK example template. Start [here](https://sdk.vercel.ai/docs/introduction) at the AI SDK documentation and reference further details [here](https://sdk.vercel.ai/docs/guides/multi-modal-chatbot) and use of the Vercel AI SDK with RSCs [here](https://sdk.vercel.ai/docs/ai-sdk-rsc).

Definitely read through the [PRs](https://github.com/vercel/ai-chatbot/pulls) though, to know what's outstanding.

This is less of a site add-on "chatbot" per se than a full web-base chat app.
